version: '3.8'
services:
  test-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: gymfuel_test
      POSTGRES_PASSWORD: gymfuel_test
      POSTGRES_DB: gymfuel_test
    ports:
      - '5433:5432' # Different port to avoid conflicts
    volumes:
      - test_db_data:/var/lib/postgresql/data
      - ./scripts/init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U gymfuel_test -d gymfuel_test']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  test_db_data:
