version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: gymfuel
      POSTGRES_PASSWORD: gymfuel
      POSTGRES_DB: gymfuel
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U gymfuel -d gymfuel']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
