name: CI Pipeline

on:
  push:
    branches: [aws-stg, aws-prod]
  pull_request:
    branches: [aws-stg, aws-prod]
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '20'

jobs:
  # Pull Request Checks
  quality-checks:
    uses: ./.github/workflows/quality-checks.yml
    if: github.event_name == 'pull_request' || github.event_name == 'push' # ✅ Added the condition
    with:
      node-version: '20'
